/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeman1;

import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.Openpdf;
import dao.BillDao;
import dao.CategoryDao;
import dao.CustomerDao;
import dao.ProductDao;
import dao.UserDao;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Customer;
import model.Product;

/**
 *
 * @author user
 */
public class PlaceOrder extends javax.swing.JFrame {

    public int mahd = 1;
    public int tongtienhoadon = 0;
    public int tongtiensanpham = 0;
    public int giasp = 0;
    public String mobilePatternString = "^[0-9]*$";
    public String useremail;
    DecimalFormat formatter = new DecimalFormat("###,###,###");

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        initComponents();
        txtNameproduct.setEditable(false);
        txtPrice.setEditable(false);
        txtTotal.setEditable(false);
        btnaddtocart.setEnabled(false);
        btngeneratebill.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) txtquanlity.getEditor()).getTextField();
        tf.setEditable(false);
        useremail = email;
    }

    public void ProductNameByCategory(String category) throws ClassNotFoundException {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getTen_hh()});
        }
    }

    public void filterProductByName(String name, String category) throws ClassNotFoundException {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.filterProductByName(name, category);
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getTen_hh()});
        }
    }

    public void clear() {
        txtNameproduct.setText("");
        txtPrice.setText("");
        txtquanlity.setValue(1);
        txtTotal.setText("");
        btnaddtocart.setEnabled(false);
    }

    public void ValidateField() {
        String tenkh = txttenkh.getText();
        String sdt = txtsdt.getText();
        if (sdt.matches(mobilePatternString) && sdt.length() == 10 && tongtienhoadon > 0) {
            btngeneratebill.setEnabled(true);
        } else {
            btngeneratebill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttenkh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtNameproduct = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtquanlity = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnaddtocart = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtgeneratetotal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btngeneratebill = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("Tạo Hóa Đơn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 19, 141, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID hóa đơn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 102, 95, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("00");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 102, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thông tin khách hàng :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 143, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên khách hàng");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 185, 123, -1));

        txttenkh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttenkh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttenkhKeyReleased(evt);
            }
        });
        getContentPane().add(txttenkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 223, 246, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số điện thoại");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 283, 107, -1));

        txtsdt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsdtKeyReleased(evt);
            }
        });
        getContentPane().add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 339, 246, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Loại sản phẩm");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 102, 113, -1));

        cbcategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 140, 242, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tìm kiếm");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 185, 80, -1));

        txtsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 223, 242, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 283, 242, 366));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên sản phẩm");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 102, 105, -1));

        txtNameproduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtNameproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 140, 228, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Giá sản phẩm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 102, -1, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 119, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số lượng");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 185, 81, -1));

        txtquanlity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtquanlity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtquanlityStateChanged(evt);
            }
        });
        getContentPane().add(txtquanlity, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 223, 228, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tổng giá");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 185, 64, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 223, 119, -1));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Giá sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 283, 640, 366));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VND");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 146, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("VND");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 229, 30, -1));

        btnaddtocart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnaddtocart.setForeground(new java.awt.Color(255, 0, 51));
        btnaddtocart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnaddtocart.setText("Thêm vào hóa đơn");
        btnaddtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtocartActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 140, 210, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnclear.setText("Xóa");
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 223, 210, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tổng tiền thanh toán :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 690, -1, -1));

        txtgeneratetotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtgeneratetotal.setForeground(new java.awt.Color(255, 255, 255));
        txtgeneratetotal.setText("000");
        txtgeneratetotal.setToolTipText("");
        getContentPane().add(txtgeneratetotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 690, 94, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("VND");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 690, 43, -1));

        btngeneratebill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btngeneratebill.setForeground(new java.awt.Color(255, 0, 0));
        btngeneratebill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btngeneratebill.setText("Tạo hóa đơn");
        btngeneratebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratebillActionPerformed(evt);
            }
        });
        getContentPane().add(btngeneratebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 687, 179, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, 40, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtocartActionPerformed
        String name = txtNameproduct.getText();
        String price = txtPrice.getText();
        String quanlity = String.valueOf(txtquanlity.getValue());
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.addRow(new Object[]{name, price, quanlity, tongtiensanpham});
        tongtienhoadon += tongtiensanpham;
        txtgeneratetotal.setText(formatter.format(tongtienhoadon));
        clear();
        ValidateField();
    }//GEN-LAST:event_btnaddtocartActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        new Home(useremail).setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            mahd = Integer.parseInt(BillDao.getId());
            txtID.setText(BillDao.getId());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ArrayList<Category> list = CategoryDao.getAllRecords();
            Iterator<Category> itr = list.iterator();
            while (itr.hasNext()) {
                Category categoryObj = itr.next();
                cbcategory.addItem(categoryObj.getTen_lh());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        String category = (String) cbcategory.getSelectedItem();
        try {
            ProductNameByCategory(category);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        String name = txtsearch.getText();
        String category = (String) cbcategory.getSelectedItem();
        try {
            filterProductByName(name, category);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String productname = model.getValueAt(index, 0).toString();
        try {
            Product product = ProductDao.getProductByName(productname);
            txtNameproduct.setText(product.getTen_hh());
            txtPrice.setText(formatter.format(Integer.parseInt(product.getGia_hh())));
            txtquanlity.setValue(1);
            //int txttotaltemp=Integer.parseInt(product.getGia_hh());
            txtTotal.setText(formatter.format(Integer.parseInt(product.getGia_hh())));
            giasp = Integer.parseInt(product.getGia_hh());
            tongtiensanpham = Integer.parseInt(product.getGia_hh());
            btnaddtocart.setEnabled(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtquanlityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtquanlityStateChanged
        int quanlity = (Integer) txtquanlity.getValue();
        if (quanlity <= 1) {
            txtquanlity.setValue(1);
            quanlity = 1;
        }
        tongtiensanpham = giasp * quanlity;
        txtTotal.setText(formatter.format(tongtiensanpham));
    }//GEN-LAST:event_txtquanlityStateChanged

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        String category = (String) cbcategory.getSelectedItem();
        try {
            ProductNameByCategory(category);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbcategoryActionPerformed

    private void txttenkhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttenkhKeyReleased
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_txttenkhKeyReleased

    private void txtsdtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsdtKeyReleased
        // TODO add your handling code here:
        ValidateField();
    }//GEN-LAST:event_txtsdtKeyReleased

    private void btngeneratebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratebillActionPerformed
        String Customname = txttenkh.getText();
        String Customsdt = txtsdt.getText();
        Customer cus = new Customer();
        cus.setTen_kh(Customname);
        cus.setSdt_kh(Customsdt);
        Bill bill = new Bill();
        String idbill;
        try {
            idbill = BillDao.getId();
            bill.setMa_hd(Integer.parseInt(idbill));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            CustomerDao.save(cus);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss");
        Date date = new Date();
        String thistime = dFormat.format(date);
        String total = String.valueOf(tongtienhoadon);
        String createdBy = useremail;
        String namenv = null;
        try {
            namenv = UserDao.getNameByEmail(useremail);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        int idkh;
        try {
            idkh = CustomerDao.getIdBySdt(Customsdt);
            bill.setMa_kh(idkh);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        int idnv;
        try {
            idnv = UserDao.getIdByEmail(useremail);
            bill.setMa_nv(idnv);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        bill.setNgaylap(thistime);
        bill.setTongtien(total);
        try {
            BillDao.save(bill);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

        String path = "C:\\Dulieuhoadon\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            //Font f = new Font(BaseFont.createFont("C:\\Users\\user\\Downloads\\fontvn\\TIMES.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED));
            //f.setStyle(Font.BOLD);
            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + bill.getMa_hd() + ".pdf"));
            doc.open();
            Paragraph cafename = new Paragraph("                                                     CafeMan Bill");
            doc.add(cafename);
            Paragraph line1 = new Paragraph("****************************************************************************************************************");
            doc.add(line1);
            Paragraph par = new Paragraph("\tMa hoa don:" + bill.getMa_hd() + "\n Ten khach hang:" + Customname + "\n Ngay lap hoa don:" + thistime);
            doc.add(par);
            doc.add(line1);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Ten San Pham");
            tbl.addCell("Gia");
            tbl.addCell("So luong");
            tbl.addCell("Thanh tien");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String a = jTable2.getValueAt(i, 0).toString();
                String b = jTable2.getValueAt(i, 1).toString();
                String c = jTable2.getValueAt(i, 2).toString();
                String d = jTable2.getValueAt(i, 3).toString();
                tbl.addCell(a);
                tbl.addCell(b);
                tbl.addCell(c);
                tbl.addCell(d);
                int idhh= ProductDao.getIdbyName(a);
                ProductDao.savechitietbanhang(bill.getMa_hd(),idhh,c);
            }
            doc.add(tbl);
            doc.add(line1);
            Paragraph grandtotal =new Paragraph("Tong tien thanh toan: "+ tongtienhoadon+" VND");
            doc.add(grandtotal);
            Paragraph nvcre =new Paragraph("Nhan vien lap: "+namenv);
            Paragraph thankM = new Paragraph("Thank you, please visit again !!");
            doc.add(thankM);
            Openpdf.OpenDpf(String.valueOf(bill.getMa_hd()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        setVisible(false);
        new PlaceOrder(createdBy).setVisible(true);
    }//GEN-LAST:event_btngeneratebillActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int index=jTable2.getSelectedRow();
        int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa sản phẩm này ra khỏi danh sách?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model =jTable2.getModel();
            String total = model.getValueAt(index, 3).toString();
            tongtienhoadon-=Integer.parseInt(total);
            txtgeneratetotal.setText(String.valueOf(tongtienhoadon));
            ((DefaultTableModel) jTable2.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnaddtocart;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btngeneratebill;
    private javax.swing.JComboBox<String> cbcategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtNameproduct;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtgeneratetotal;
    private javax.swing.JSpinner txtquanlity;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txttenkh;
    // End of variables declaration//GEN-END:variables
}
